CREATE DATABASE lsi_10k;
USE lsi_10k;
CREATE TABLE AN2 (
	fk_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	cell_name VARCHAR(100),
	pin_A VARCHAR(100),
	pin_B VARCHAR(100),
	pin_Z VARCHAR(100),
);
CREATE TABLE OR2 (
	fk_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	cell_name VARCHAR(100),
	pin_A VARCHAR(100),
	pin_B VARCHAR(100),
	pin_Z VARCHAR(100),
);
CREATE TABLE IV (
	fk_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	cell_name VARCHAR(100),
	pin_A VARCHAR(100),
	pin_Z VARCHAR(100),
);
CREATE TABLE IVP (
	fk_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	cell_name VARCHAR(100),
	pin_A VARCHAR(100),
	pin_Z VARCHAR(100),
);
CREATE TABLE IVA (
	fk_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	cell_name VARCHAR(100),
	pin_A VARCHAR(100),
	pin_Z VARCHAR(100),
);
CREATE TABLE IVAP (
	fk_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	cell_name VARCHAR(100),
	pin_A VARCHAR(100),
	pin_Z VARCHAR(100),
);
CREATE TABLE IVDA (
	fk_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	cell_name VARCHAR(100),
	pin_A VARCHAR(100),
	pin_Y VARCHAR(100),
	pin_Z VARCHAR(100),
);
CREATE TABLE IVDAP (
	fk_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	cell_name VARCHAR(100),
	pin_A VARCHAR(100),
	pin_Y VARCHAR(100),
	pin_Z VARCHAR(100),
);
CREATE TABLE B5I (
	fk_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	cell_name VARCHAR(100),
	pin_A VARCHAR(100),
	pin_Z VARCHAR(100),
);
CREATE TABLE B5IP (
	fk_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	cell_name VARCHAR(100),
	pin_A VARCHAR(100),
	pin_Z VARCHAR(100),
);
CREATE TABLE B4I (
	fk_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	cell_name VARCHAR(100),
	pin_A VARCHAR(100),
	pin_Z VARCHAR(100),
);
CREATE TABLE B4IP (
	fk_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	cell_name VARCHAR(100),
	pin_A VARCHAR(100),
	pin_Z VARCHAR(100),
);
CREATE TABLE ND2 (
	fk_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	cell_name VARCHAR(100),
	pin_A VARCHAR(100),
	pin_B VARCHAR(100),
	pin_Z VARCHAR(100),
);
CREATE TABLE ND2P (
	fk_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	cell_name VARCHAR(100),
	pin_A VARCHAR(100),
	pin_B VARCHAR(100),
	pin_Z VARCHAR(100),
);
CREATE TABLE NR2 (
	fk_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	cell_name VARCHAR(100),
	pin_A VARCHAR(100),
	pin_B VARCHAR(100),
	pin_Z VARCHAR(100),
);
CREATE TABLE NR2P (
	fk_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	cell_name VARCHAR(100),
	pin_A VARCHAR(100),
	pin_B VARCHAR(100),
	pin_Z VARCHAR(100),
);
CREATE TABLE EN (
	fk_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	cell_name VARCHAR(100),
	pin_A VARCHAR(100),
	pin_B VARCHAR(100),
	pin_Z VARCHAR(100),
);
CREATE TABLE EO (
	fk_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	cell_name VARCHAR(100),
	pin_A VARCHAR(100),
	pin_B VARCHAR(100),
	pin_Z VARCHAR(100),
);
CREATE TABLE ND3 (
	fk_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	cell_name VARCHAR(100),
	pin_A VARCHAR(100),
	pin_B VARCHAR(100),
	pin_C VARCHAR(100),
	pin_Z VARCHAR(100),
);
CREATE TABLE ND3P (
	fk_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	cell_name VARCHAR(100),
	pin_A VARCHAR(100),
	pin_B VARCHAR(100),
	pin_C VARCHAR(100),
	pin_Z VARCHAR(100),
);
CREATE TABLE NR3 (
	fk_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	cell_name VARCHAR(100),
	pin_A VARCHAR(100),
	pin_B VARCHAR(100),
	pin_C VARCHAR(100),
	pin_Z VARCHAR(100),
);
CREATE TABLE NR3P (
	fk_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	cell_name VARCHAR(100),
	pin_A VARCHAR(100),
	pin_B VARCHAR(100),
	pin_C VARCHAR(100),
	pin_Z VARCHAR(100),
);
CREATE TABLE AN3 (
	fk_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	cell_name VARCHAR(100),
	pin_A VARCHAR(100),
	pin_B VARCHAR(100),
	pin_C VARCHAR(100),
	pin_Z VARCHAR(100),
);
CREATE TABLE OR3 (
	fk_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	cell_name VARCHAR(100),
	pin_A VARCHAR(100),
	pin_B VARCHAR(100),
	pin_C VARCHAR(100),
	pin_Z VARCHAR(100),
);
CREATE TABLE ND4 (
	fk_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	cell_name VARCHAR(100),
	pin_A VARCHAR(100),
	pin_B VARCHAR(100),
	pin_C VARCHAR(100),
	pin_D VARCHAR(100),
	pin_Z VARCHAR(100),
);
CREATE TABLE ND4P (
	fk_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	cell_name VARCHAR(100),
	pin_A VARCHAR(100),
	pin_B VARCHAR(100),
	pin_C VARCHAR(100),
	pin_D VARCHAR(100),
	pin_Z VARCHAR(100),
);
CREATE TABLE NR4 (
	fk_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	cell_name VARCHAR(100),
	pin_A VARCHAR(100),
	pin_B VARCHAR(100),
	pin_C VARCHAR(100),
	pin_D VARCHAR(100),
	pin_Z VARCHAR(100),
);
CREATE TABLE ND5 (
	fk_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	cell_name VARCHAR(100),
	pin_A VARCHAR(100),
	pin_B VARCHAR(100),
	pin_C VARCHAR(100),
	pin_D VARCHAR(100),
	pin_E VARCHAR(100),
	pin_Z VARCHAR(100),
);
CREATE TABLE AO6 (
	fk_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	cell_name VARCHAR(100),
	pin_A VARCHAR(100),
	pin_B VARCHAR(100),
	pin_C VARCHAR(100),
	pin_Z VARCHAR(100),
);
CREATE TABLE AO6P (
	fk_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	cell_name VARCHAR(100),
	pin_A VARCHAR(100),
	pin_B VARCHAR(100),
	pin_C VARCHAR(100),
	pin_Z VARCHAR(100),
);
CREATE TABLE AO7 (
	fk_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	cell_name VARCHAR(100),
	pin_A VARCHAR(100),
	pin_B VARCHAR(100),
	pin_C VARCHAR(100),
	pin_Z VARCHAR(100),
);
CREATE TABLE AO7P (
	fk_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	cell_name VARCHAR(100),
	pin_A VARCHAR(100),
	pin_B VARCHAR(100),
	pin_C VARCHAR(100),
	pin_Z VARCHAR(100),
);
CREATE TABLE AO2 (
	fk_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	cell_name VARCHAR(100),
	pin_A VARCHAR(100),
	pin_B VARCHAR(100),
	pin_C VARCHAR(100),
	pin_D VARCHAR(100),
	pin_Z VARCHAR(100),
);
CREATE TABLE AO2P (
	fk_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	cell_name VARCHAR(100),
	pin_A VARCHAR(100),
	pin_B VARCHAR(100),
	pin_C VARCHAR(100),
	pin_D VARCHAR(100),
	pin_Z VARCHAR(100),
);
CREATE TABLE AO4 (
	fk_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	cell_name VARCHAR(100),
	pin_A VARCHAR(100),
	pin_B VARCHAR(100),
	pin_C VARCHAR(100),
	pin_D VARCHAR(100),
	pin_Z VARCHAR(100),
);
CREATE TABLE AO4P (
	fk_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	cell_name VARCHAR(100),
	pin_A VARCHAR(100),
	pin_B VARCHAR(100),
	pin_C VARCHAR(100),
	pin_D VARCHAR(100),
	pin_Z VARCHAR(100),
);
CREATE TABLE AO1 (
	fk_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	cell_name VARCHAR(100),
	pin_A VARCHAR(100),
	pin_B VARCHAR(100),
	pin_C VARCHAR(100),
	pin_D VARCHAR(100),
	pin_Z VARCHAR(100),
);
CREATE TABLE AO3 (
	fk_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	cell_name VARCHAR(100),
	pin_A VARCHAR(100),
	pin_B VARCHAR(100),
	pin_C VARCHAR(100),
	pin_D VARCHAR(100),
	pin_Z VARCHAR(100),
);
CREATE TABLE AO11 (
	fk_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	cell_name VARCHAR(100),
	pin_A VARCHAR(100),
	pin_B VARCHAR(100),
	pin_C VARCHAR(100),
	pin_D VARCHAR(100),
	pin_E VARCHAR(100),
	pin_F VARCHAR(100),
	pin_Z VARCHAR(100),
);
CREATE TABLE AN2P (
	fk_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	cell_name VARCHAR(100),
	pin_A VARCHAR(100),
	pin_B VARCHAR(100),
	pin_Z VARCHAR(100),
);
CREATE TABLE AN3P (
	fk_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	cell_name VARCHAR(100),
	pin_A VARCHAR(100),
	pin_B VARCHAR(100),
	pin_C VARCHAR(100),
	pin_Z VARCHAR(100),
);
CREATE TABLE AN4 (
	fk_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	cell_name VARCHAR(100),
	pin_A VARCHAR(100),
	pin_B VARCHAR(100),
	pin_C VARCHAR(100),
	pin_D VARCHAR(100),
	pin_Z VARCHAR(100),
);
CREATE TABLE AN4P (
	fk_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	cell_name VARCHAR(100),
	pin_A VARCHAR(100),
	pin_B VARCHAR(100),
	pin_C VARCHAR(100),
	pin_D VARCHAR(100),
	pin_Z VARCHAR(100),
);
CREATE TABLE OR2P (
	fk_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	cell_name VARCHAR(100),
	pin_A VARCHAR(100),
	pin_B VARCHAR(100),
	pin_Z VARCHAR(100),
);
CREATE TABLE OR3P (
	fk_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	cell_name VARCHAR(100),
	pin_A VARCHAR(100),
	pin_B VARCHAR(100),
	pin_C VARCHAR(100),
	pin_Z VARCHAR(100),
);
CREATE TABLE OR4 (
	fk_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	cell_name VARCHAR(100),
	pin_A VARCHAR(100),
	pin_B VARCHAR(100),
	pin_C VARCHAR(100),
	pin_D VARCHAR(100),
	pin_Z VARCHAR(100),
);
CREATE TABLE OR4P (
	fk_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	cell_name VARCHAR(100),
	pin_A VARCHAR(100),
	pin_B VARCHAR(100),
	pin_C VARCHAR(100),
	pin_D VARCHAR(100),
	pin_Z VARCHAR(100),
);
CREATE TABLE MUX21H (
	fk_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	cell_name VARCHAR(100),
	pin_A VARCHAR(100),
	pin_B VARCHAR(100),
	pin_S VARCHAR(100),
	pin_Z VARCHAR(100),
);
CREATE TABLE MUX41 (
	fk_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	cell_name VARCHAR(100),
	pin_D0 VARCHAR(100),
	pin_D1 VARCHAR(100),
	pin_D2 VARCHAR(100),
	pin_D3 VARCHAR(100),
	pin_A VARCHAR(100),
	pin_B VARCHAR(100),
	pin_Z VARCHAR(100),
);
CREATE TABLE NR5 (
	fk_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	cell_name VARCHAR(100),
	pin_A VARCHAR(100),
	pin_B VARCHAR(100),
	pin_C VARCHAR(100),
	pin_D VARCHAR(100),
	pin_E VARCHAR(100),
	pin_Z VARCHAR(100),
);
CREATE TABLE ND6 (
	fk_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	cell_name VARCHAR(100),
	pin_A VARCHAR(100),
	pin_B VARCHAR(100),
	pin_C VARCHAR(100),
	pin_D VARCHAR(100),
	pin_E VARCHAR(100),
	pin_F VARCHAR(100),
	pin_Z VARCHAR(100),
);
CREATE TABLE NR6 (
	fk_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	cell_name VARCHAR(100),
	pin_A VARCHAR(100),
	pin_B VARCHAR(100),
	pin_C VARCHAR(100),
	pin_D VARCHAR(100),
	pin_E VARCHAR(100),
	pin_F VARCHAR(100),
	pin_Z VARCHAR(100),
);
CREATE TABLE ND8 (
	fk_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	cell_name VARCHAR(100),
	pin_A VARCHAR(100),
	pin_B VARCHAR(100),
	pin_C VARCHAR(100),
	pin_D VARCHAR(100),
	pin_E VARCHAR(100),
	pin_F VARCHAR(100),
	pin_G VARCHAR(100),
	pin_H VARCHAR(100),
	pin_Z VARCHAR(100),
);
CREATE TABLE NR8 (
	fk_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	cell_name VARCHAR(100),
	pin_A VARCHAR(100),
	pin_B VARCHAR(100),
	pin_C VARCHAR(100),
	pin_D VARCHAR(100),
	pin_E VARCHAR(100),
	pin_F VARCHAR(100),
	pin_G VARCHAR(100),
	pin_H VARCHAR(100),
	pin_Z VARCHAR(100),
);
CREATE TABLE EON1 (
	fk_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	cell_name VARCHAR(100),
	pin_A VARCHAR(100),
	pin_B VARCHAR(100),
	pin_C VARCHAR(100),
	pin_D VARCHAR(100),
	pin_Z VARCHAR(100),
);
CREATE TABLE EO1 (
	fk_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	cell_name VARCHAR(100),
	pin_A VARCHAR(100),
	pin_B VARCHAR(100),
	pin_C VARCHAR(100),
	pin_D VARCHAR(100),
	pin_Z VARCHAR(100),
);
CREATE TABLE ND5P (
	fk_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	cell_name VARCHAR(100),
	pin_A VARCHAR(100),
	pin_B VARCHAR(100),
	pin_C VARCHAR(100),
	pin_D VARCHAR(100),
	pin_E VARCHAR(100),
	pin_Z VARCHAR(100),
);
CREATE TABLE NR5P (
	fk_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	cell_name VARCHAR(100),
	pin_A VARCHAR(100),
	pin_B VARCHAR(100),
	pin_C VARCHAR(100),
	pin_D VARCHAR(100),
	pin_E VARCHAR(100),
	pin_Z VARCHAR(100),
);
CREATE TABLE ND6P (
	fk_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	cell_name VARCHAR(100),
	pin_A VARCHAR(100),
	pin_B VARCHAR(100),
	pin_C VARCHAR(100),
	pin_D VARCHAR(100),
	pin_E VARCHAR(100),
	pin_F VARCHAR(100),
	pin_Z VARCHAR(100),
);
CREATE TABLE NR6P (
	fk_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	cell_name VARCHAR(100),
	pin_A VARCHAR(100),
	pin_B VARCHAR(100),
	pin_C VARCHAR(100),
	pin_D VARCHAR(100),
	pin_E VARCHAR(100),
	pin_F VARCHAR(100),
	pin_Z VARCHAR(100),
);
CREATE TABLE ND8P (
	fk_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	cell_name VARCHAR(100),
	pin_A VARCHAR(100),
	pin_B VARCHAR(100),
	pin_C VARCHAR(100),
	pin_D VARCHAR(100),
	pin_E VARCHAR(100),
	pin_F VARCHAR(100),
	pin_G VARCHAR(100),
	pin_H VARCHAR(100),
	pin_Z VARCHAR(100),
);
CREATE TABLE NR8P (
	fk_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	cell_name VARCHAR(100),
	pin_A VARCHAR(100),
	pin_B VARCHAR(100),
	pin_C VARCHAR(100),
	pin_D VARCHAR(100),
	pin_E VARCHAR(100),
	pin_F VARCHAR(100),
	pin_G VARCHAR(100),
	pin_H VARCHAR(100),
	pin_Z VARCHAR(100),
);
CREATE TABLE NR16 (
	fk_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	cell_name VARCHAR(100),
	pin_I0 VARCHAR(100),
	pin_I1 VARCHAR(100),
	pin_I2 VARCHAR(100),
	pin_I3 VARCHAR(100),
	pin_I4 VARCHAR(100),
	pin_I5 VARCHAR(100),
	pin_I6 VARCHAR(100),
	pin_I7 VARCHAR(100),
	pin_I8 VARCHAR(100),
	pin_I9 VARCHAR(100),
	pin_I10 VARCHAR(100),
	pin_I11 VARCHAR(100),
	pin_I12 VARCHAR(100),
	pin_I13 VARCHAR(100),
	pin_I14 VARCHAR(100),
	pin_I15 VARCHAR(100),
	pin_Z VARCHAR(100),
);
CREATE TABLE NR16P (
	fk_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	cell_name VARCHAR(100),
	pin_I0 VARCHAR(100),
	pin_I1 VARCHAR(100),
	pin_I2 VARCHAR(100),
	pin_I3 VARCHAR(100),
	pin_I4 VARCHAR(100),
	pin_I5 VARCHAR(100),
	pin_I6 VARCHAR(100),
	pin_I7 VARCHAR(100),
	pin_I8 VARCHAR(100),
	pin_I9 VARCHAR(100),
	pin_I10 VARCHAR(100),
	pin_I11 VARCHAR(100),
	pin_I12 VARCHAR(100),
	pin_I13 VARCHAR(100),
	pin_I14 VARCHAR(100),
	pin_I15 VARCHAR(100),
	pin_Z VARCHAR(100),
);
CREATE TABLE ENP (
	fk_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	cell_name VARCHAR(100),
	pin_A VARCHAR(100),
	pin_B VARCHAR(100),
	pin_Z VARCHAR(100),
);
CREATE TABLE EOP (
	fk_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	cell_name VARCHAR(100),
	pin_A VARCHAR(100),
	pin_B VARCHAR(100),
	pin_Z VARCHAR(100),
);
CREATE TABLE EO1P (
	fk_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	cell_name VARCHAR(100),
	pin_A VARCHAR(100),
	pin_B VARCHAR(100),
	pin_C VARCHAR(100),
	pin_D VARCHAR(100),
	pin_Z VARCHAR(100),
);
CREATE TABLE EON1P (
	fk_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	cell_name VARCHAR(100),
	pin_A VARCHAR(100),
	pin_B VARCHAR(100),
	pin_C VARCHAR(100),
	pin_D VARCHAR(100),
	pin_Z VARCHAR(100),
);
CREATE TABLE AO1P (
	fk_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	cell_name VARCHAR(100),
	pin_A VARCHAR(100),
	pin_B VARCHAR(100),
	pin_C VARCHAR(100),
	pin_D VARCHAR(100),
	pin_Z VARCHAR(100),
);
CREATE TABLE AO3P (
	fk_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	cell_name VARCHAR(100),
	pin_A VARCHAR(100),
	pin_B VARCHAR(100),
	pin_C VARCHAR(100),
	pin_D VARCHAR(100),
	pin_Z VARCHAR(100),
);
CREATE TABLE AO11P (
	fk_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	cell_name VARCHAR(100),
	pin_A VARCHAR(100),
	pin_B VARCHAR(100),
	pin_C VARCHAR(100),
	pin_D VARCHAR(100),
	pin_E VARCHAR(100),
	pin_F VARCHAR(100),
	pin_Z VARCHAR(100),
);
CREATE TABLE MUX21HP (
	fk_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	cell_name VARCHAR(100),
	pin_A VARCHAR(100),
	pin_B VARCHAR(100),
	pin_S VARCHAR(100),
	pin_Z VARCHAR(100),
);
CREATE TABLE MUX21L (
	fk_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	cell_name VARCHAR(100),
	pin_A VARCHAR(100),
	pin_B VARCHAR(100),
	pin_S VARCHAR(100),
	pin_Z VARCHAR(100),
);
CREATE TABLE MUX21LP (
	fk_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	cell_name VARCHAR(100),
	pin_A VARCHAR(100),
	pin_B VARCHAR(100),
	pin_S VARCHAR(100),
	pin_Z VARCHAR(100),
);
CREATE TABLE MUX31L (
	fk_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	cell_name VARCHAR(100),
	pin_D0 VARCHAR(100),
	pin_D1 VARCHAR(100),
	pin_D2 VARCHAR(100),
	pin_A VARCHAR(100),
	pin_B VARCHAR(100),
	pin_Z VARCHAR(100),
);
CREATE TABLE MUX31LP (
	fk_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	cell_name VARCHAR(100),
	pin_D0 VARCHAR(100),
	pin_D1 VARCHAR(100),
	pin_D2 VARCHAR(100),
	pin_A VARCHAR(100),
	pin_B VARCHAR(100),
	pin_Z VARCHAR(100),
);
CREATE TABLE MUX41P (
	fk_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	cell_name VARCHAR(100),
	pin_D0 VARCHAR(100),
	pin_D1 VARCHAR(100),
	pin_D2 VARCHAR(100),
	pin_D3 VARCHAR(100),
	pin_A VARCHAR(100),
	pin_B VARCHAR(100),
	pin_Z VARCHAR(100),
);
CREATE TABLE MUX21LA (
	fk_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	cell_name VARCHAR(100),
	pin_SN VARCHAR(100),
	pin_A VARCHAR(100),
	pin_S VARCHAR(100),
	pin_B VARCHAR(100),
	pin_Z VARCHAR(100),
);
CREATE TABLE MUX51H (
	fk_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	cell_name VARCHAR(100),
	pin_D0 VARCHAR(100),
	pin_D1 VARCHAR(100),
	pin_D2 VARCHAR(100),
	pin_D3 VARCHAR(100),
	pin_D4 VARCHAR(100),
	pin_A VARCHAR(100),
	pin_B VARCHAR(100),
	pin_C VARCHAR(100),
	pin_Z VARCHAR(100),
);
CREATE TABLE MUX51HP (
	fk_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	cell_name VARCHAR(100),
	pin_D0 VARCHAR(100),
	pin_D1 VARCHAR(100),
	pin_D2 VARCHAR(100),
	pin_D3 VARCHAR(100),
	pin_D4 VARCHAR(100),
	pin_A VARCHAR(100),
	pin_B VARCHAR(100),
	pin_C VARCHAR(100),
	pin_Z VARCHAR(100),
);
CREATE TABLE MUX81 (
	fk_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	cell_name VARCHAR(100),
	pin_D0 VARCHAR(100),
	pin_D1 VARCHAR(100),
	pin_D2 VARCHAR(100),
	pin_D3 VARCHAR(100),
	pin_D4 VARCHAR(100),
	pin_D5 VARCHAR(100),
	pin_D6 VARCHAR(100),
	pin_D7 VARCHAR(100),
	pin_A VARCHAR(100),
	pin_B VARCHAR(100),
	pin_C VARCHAR(100),
	pin_Z VARCHAR(100),
);
CREATE TABLE MUX81P (
	fk_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	cell_name VARCHAR(100),
	pin_D0 VARCHAR(100),
	pin_D1 VARCHAR(100),
	pin_D2 VARCHAR(100),
	pin_D3 VARCHAR(100),
	pin_D4 VARCHAR(100),
	pin_D5 VARCHAR(100),
	pin_D6 VARCHAR(100),
	pin_D7 VARCHAR(100),
	pin_A VARCHAR(100),
	pin_B VARCHAR(100),
	pin_C VARCHAR(100),
	pin_Z VARCHAR(100),
);
CREATE TABLE AO5 (
	fk_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	cell_name VARCHAR(100),
	pin_A VARCHAR(100),
	pin_B VARCHAR(100),
	pin_C VARCHAR(100),
	pin_Z VARCHAR(100),
);
CREATE TABLE AO5P (
	fk_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	cell_name VARCHAR(100),
	pin_A VARCHAR(100),
	pin_B VARCHAR(100),
	pin_C VARCHAR(100),
	pin_Z VARCHAR(100),
);
CREATE TABLE EN3 (
	fk_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	cell_name VARCHAR(100),
	pin_A VARCHAR(100),
	pin_B VARCHAR(100),
	pin_C VARCHAR(100),
	pin_Z VARCHAR(100),
);
CREATE TABLE EN3P (
	fk_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	cell_name VARCHAR(100),
	pin_A VARCHAR(100),
	pin_B VARCHAR(100),
	pin_C VARCHAR(100),
	pin_Z VARCHAR(100),
);
CREATE TABLE EO3 (
	fk_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	cell_name VARCHAR(100),
	pin_A VARCHAR(100),
	pin_B VARCHAR(100),
	pin_C VARCHAR(100),
	pin_Z VARCHAR(100),
);
CREATE TABLE EO3P (
	fk_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	cell_name VARCHAR(100),
	pin_A VARCHAR(100),
	pin_B VARCHAR(100),
	pin_C VARCHAR(100),
	pin_Z VARCHAR(100),
);
CREATE TABLE AO12 (
	fk_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	cell_name VARCHAR(100),
	pin_A VARCHAR(100),
	pin_B VARCHAR(100),
	pin_C VARCHAR(100),
	pin_D VARCHAR(100),
	pin_E VARCHAR(100),
	pin_F VARCHAR(100),
	pin_G VARCHAR(100),
	pin_H VARCHAR(100),
	pin_Z VARCHAR(100),
);
CREATE TABLE AO12P (
	fk_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	cell_name VARCHAR(100),
	pin_A VARCHAR(100),
	pin_B VARCHAR(100),
	pin_C VARCHAR(100),
	pin_D VARCHAR(100),
	pin_E VARCHAR(100),
	pin_F VARCHAR(100),
	pin_G VARCHAR(100),
	pin_H VARCHAR(100),
	pin_Z VARCHAR(100),
);
CREATE TABLE B1I (
	fk_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	cell_name VARCHAR(100),
	pin_A VARCHAR(100),
	pin_Z VARCHAR(100),
);
CREATE TABLE MUX21LAP (
	fk_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	cell_name VARCHAR(100),
	pin_SN VARCHAR(100),
	pin_A VARCHAR(100),
	pin_S VARCHAR(100),
	pin_B VARCHAR(100),
	pin_Z VARCHAR(100),
);
CREATE TABLE NR4P (
	fk_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	cell_name VARCHAR(100),
	pin_A VARCHAR(100),
	pin_B VARCHAR(100),
	pin_C VARCHAR(100),
	pin_D VARCHAR(100),
	pin_Z VARCHAR(100),
);
CREATE TABLE FD1 (
	fk_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	cell_name VARCHAR(100),
	pin_D VARCHAR(100),
	pin_CP VARCHAR(100),
	pin_Q VARCHAR(100),
	pin_QN VARCHAR(100),
);
CREATE TABLE FD1P (
	fk_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	cell_name VARCHAR(100),
	pin_D VARCHAR(100),
	pin_CP VARCHAR(100),
	pin_Q VARCHAR(100),
	pin_QN VARCHAR(100),
);
CREATE TABLE FD1S (
	fk_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	cell_name VARCHAR(100),
	pin_D VARCHAR(100),
	pin_CP VARCHAR(100),
	pin_TI VARCHAR(100),
	pin_TE VARCHAR(100),
	pin_Q VARCHAR(100),
	pin_QN VARCHAR(100),
);
CREATE TABLE FD1SP (
	fk_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	cell_name VARCHAR(100),
	pin_D VARCHAR(100),
	pin_CP VARCHAR(100),
	pin_TI VARCHAR(100),
	pin_TE VARCHAR(100),
	pin_Q VARCHAR(100),
	pin_QN VARCHAR(100),
);
CREATE TABLE FD2 (
	fk_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	cell_name VARCHAR(100),
	pin_D VARCHAR(100),
	pin_CP VARCHAR(100),
	pin_CD VARCHAR(100),
	pin_Q VARCHAR(100),
	pin_QN VARCHAR(100),
);
CREATE TABLE FD2P (
	fk_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	cell_name VARCHAR(100),
	pin_D VARCHAR(100),
	pin_CP VARCHAR(100),
	pin_CD VARCHAR(100),
	pin_Q VARCHAR(100),
	pin_QN VARCHAR(100),
);
CREATE TABLE FD2S (
	fk_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	cell_name VARCHAR(100),
	pin_D VARCHAR(100),
	pin_CP VARCHAR(100),
	pin_CD VARCHAR(100),
	pin_TI VARCHAR(100),
	pin_TE VARCHAR(100),
	pin_Q VARCHAR(100),
	pin_QN VARCHAR(100),
);
CREATE TABLE FD2SP (
	fk_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	cell_name VARCHAR(100),
	pin_D VARCHAR(100),
	pin_CP VARCHAR(100),
	pin_CD VARCHAR(100),
	pin_TI VARCHAR(100),
	pin_TE VARCHAR(100),
	pin_Q VARCHAR(100),
	pin_QN VARCHAR(100),
);
CREATE TABLE FD3 (
	fk_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	cell_name VARCHAR(100),
	pin_D VARCHAR(100),
	pin_CP VARCHAR(100),
	pin_CD VARCHAR(100),
	pin_SD VARCHAR(100),
	pin_Q VARCHAR(100),
	pin_QN VARCHAR(100),
);
CREATE TABLE FD3P (
	fk_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	cell_name VARCHAR(100),
	pin_D VARCHAR(100),
	pin_CP VARCHAR(100),
	pin_CD VARCHAR(100),
	pin_SD VARCHAR(100),
	pin_Q VARCHAR(100),
	pin_QN VARCHAR(100),
);
CREATE TABLE FD3S (
	fk_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	cell_name VARCHAR(100),
	pin_D VARCHAR(100),
	pin_CP VARCHAR(100),
	pin_CD VARCHAR(100),
	pin_SD VARCHAR(100),
	pin_TI VARCHAR(100),
	pin_TE VARCHAR(100),
	pin_Q VARCHAR(100),
	pin_QN VARCHAR(100),
);
CREATE TABLE FD3SP (
	fk_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	cell_name VARCHAR(100),
	pin_D VARCHAR(100),
	pin_CP VARCHAR(100),
	pin_CD VARCHAR(100),
	pin_SD VARCHAR(100),
	pin_TI VARCHAR(100),
	pin_TE VARCHAR(100),
	pin_Q VARCHAR(100),
	pin_QN VARCHAR(100),
);
CREATE TABLE FD4 (
	fk_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	cell_name VARCHAR(100),
	pin_D VARCHAR(100),
	pin_CP VARCHAR(100),
	pin_SD VARCHAR(100),
	pin_Q VARCHAR(100),
	pin_QN VARCHAR(100),
);
CREATE TABLE FD4P (
	fk_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	cell_name VARCHAR(100),
	pin_D VARCHAR(100),
	pin_CP VARCHAR(100),
	pin_SD VARCHAR(100),
	pin_Q VARCHAR(100),
	pin_QN VARCHAR(100),
);
CREATE TABLE FD4S (
	fk_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	cell_name VARCHAR(100),
	pin_D VARCHAR(100),
	pin_CP VARCHAR(100),
	pin_SD VARCHAR(100),
	pin_TI VARCHAR(100),
	pin_TE VARCHAR(100),
	pin_Q VARCHAR(100),
	pin_QN VARCHAR(100),
);
CREATE TABLE FD4SP (
	fk_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	cell_name VARCHAR(100),
	pin_D VARCHAR(100),
	pin_CP VARCHAR(100),
	pin_SD VARCHAR(100),
	pin_TI VARCHAR(100),
	pin_TE VARCHAR(100),
	pin_Q VARCHAR(100),
	pin_QN VARCHAR(100),
);
CREATE TABLE FJK1 (
	fk_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	cell_name VARCHAR(100),
	pin_J VARCHAR(100),
	pin_K VARCHAR(100),
	pin_CP VARCHAR(100),
	pin_Q VARCHAR(100),
	pin_QN VARCHAR(100),
);
CREATE TABLE FJK1P (
	fk_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	cell_name VARCHAR(100),
	pin_J VARCHAR(100),
	pin_K VARCHAR(100),
	pin_CP VARCHAR(100),
	pin_Q VARCHAR(100),
	pin_QN VARCHAR(100),
);
CREATE TABLE FJK1S (
	fk_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	cell_name VARCHAR(100),
	pin_J VARCHAR(100),
	pin_K VARCHAR(100),
	pin_CP VARCHAR(100),
	pin_TI VARCHAR(100),
	pin_TE VARCHAR(100),
	pin_Q VARCHAR(100),
	pin_QN VARCHAR(100),
);
CREATE TABLE FJK1SP (
	fk_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	cell_name VARCHAR(100),
	pin_J VARCHAR(100),
	pin_K VARCHAR(100),
	pin_CP VARCHAR(100),
	pin_TI VARCHAR(100),
	pin_TE VARCHAR(100),
	pin_Q VARCHAR(100),
	pin_QN VARCHAR(100),
);
CREATE TABLE FJK2 (
	fk_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	cell_name VARCHAR(100),
	pin_J VARCHAR(100),
	pin_K VARCHAR(100),
	pin_CP VARCHAR(100),
	pin_CD VARCHAR(100),
	pin_Q VARCHAR(100),
	pin_QN VARCHAR(100),
);
CREATE TABLE FJK2P (
	fk_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	cell_name VARCHAR(100),
	pin_J VARCHAR(100),
	pin_K VARCHAR(100),
	pin_CP VARCHAR(100),
	pin_CD VARCHAR(100),
	pin_Q VARCHAR(100),
	pin_QN VARCHAR(100),
);
CREATE TABLE FJK2S (
	fk_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	cell_name VARCHAR(100),
	pin_J VARCHAR(100),
	pin_K VARCHAR(100),
	pin_CP VARCHAR(100),
	pin_CD VARCHAR(100),
	pin_TI VARCHAR(100),
	pin_TE VARCHAR(100),
	pin_Q VARCHAR(100),
	pin_QN VARCHAR(100),
);
CREATE TABLE FJK2SP (
	fk_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	cell_name VARCHAR(100),
	pin_J VARCHAR(100),
	pin_K VARCHAR(100),
	pin_CP VARCHAR(100),
	pin_CD VARCHAR(100),
	pin_TI VARCHAR(100),
	pin_TE VARCHAR(100),
	pin_Q VARCHAR(100),
	pin_QN VARCHAR(100),
);
CREATE TABLE FJK3 (
	fk_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	cell_name VARCHAR(100),
	pin_J VARCHAR(100),
	pin_K VARCHAR(100),
	pin_CP VARCHAR(100),
	pin_CD VARCHAR(100),
	pin_SD VARCHAR(100),
	pin_Q VARCHAR(100),
	pin_QN VARCHAR(100),
);
CREATE TABLE FJK3P (
	fk_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	cell_name VARCHAR(100),
	pin_J VARCHAR(100),
	pin_K VARCHAR(100),
	pin_CP VARCHAR(100),
	pin_CD VARCHAR(100),
	pin_SD VARCHAR(100),
	pin_Q VARCHAR(100),
	pin_QN VARCHAR(100),
);
CREATE TABLE FJK3S (
	fk_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	cell_name VARCHAR(100),
	pin_J VARCHAR(100),
	pin_K VARCHAR(100),
	pin_CP VARCHAR(100),
	pin_CD VARCHAR(100),
	pin_SD VARCHAR(100),
	pin_TI VARCHAR(100),
	pin_TE VARCHAR(100),
	pin_Q VARCHAR(100),
	pin_QN VARCHAR(100),
);
CREATE TABLE FJK3SP (
	fk_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	cell_name VARCHAR(100),
	pin_J VARCHAR(100),
	pin_K VARCHAR(100),
	pin_CP VARCHAR(100),
	pin_CD VARCHAR(100),
	pin_SD VARCHAR(100),
	pin_TI VARCHAR(100),
	pin_TE VARCHAR(100),
	pin_Q VARCHAR(100),
	pin_QN VARCHAR(100),
);
CREATE TABLE LD1 (
	fk_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	cell_name VARCHAR(100),
	pin_D VARCHAR(100),
	pin_G VARCHAR(100),
	pin_Q VARCHAR(100),
	pin_QN VARCHAR(100),
);
CREATE TABLE LD1P (
	fk_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	cell_name VARCHAR(100),
	pin_D VARCHAR(100),
	pin_G VARCHAR(100),
	pin_Q VARCHAR(100),
	pin_QN VARCHAR(100),
);
CREATE TABLE LD2 (
	fk_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	cell_name VARCHAR(100),
	pin_D VARCHAR(100),
	pin_GN VARCHAR(100),
	pin_Q VARCHAR(100),
	pin_QN VARCHAR(100),
);
CREATE TABLE LD2P (
	fk_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	cell_name VARCHAR(100),
	pin_D VARCHAR(100),
	pin_GN VARCHAR(100),
	pin_Q VARCHAR(100),
	pin_QN VARCHAR(100),
);
CREATE TABLE LD3 (
	fk_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	cell_name VARCHAR(100),
	pin_D VARCHAR(100),
	pin_G VARCHAR(100),
	pin_CD VARCHAR(100),
	pin_Q VARCHAR(100),
	pin_QN VARCHAR(100),
);
CREATE TABLE LD3P (
	fk_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	cell_name VARCHAR(100),
	pin_D VARCHAR(100),
	pin_G VARCHAR(100),
	pin_CD VARCHAR(100),
	pin_Q VARCHAR(100),
	pin_QN VARCHAR(100),
);
CREATE TABLE LD4 (
	fk_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	cell_name VARCHAR(100),
	pin_D VARCHAR(100),
	pin_GN VARCHAR(100),
	pin_CD VARCHAR(100),
	pin_Q VARCHAR(100),
	pin_QN VARCHAR(100),
);
CREATE TABLE LD4P (
	fk_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	cell_name VARCHAR(100),
	pin_D VARCHAR(100),
	pin_GN VARCHAR(100),
	pin_CD VARCHAR(100),
	pin_Q VARCHAR(100),
	pin_QN VARCHAR(100),
);
CREATE TABLE B2I (
	fk_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	cell_name VARCHAR(100),
	pin_A VARCHAR(100),
	pin_Z1 VARCHAR(100),
	pin_Z2 VARCHAR(100),
);
CREATE TABLE B2IP (
	fk_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	cell_name VARCHAR(100),
	pin_A VARCHAR(100),
	pin_Z1 VARCHAR(100),
	pin_Z2 VARCHAR(100),
);
CREATE TABLE B3I (
	fk_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	cell_name VARCHAR(100),
	pin_A VARCHAR(100),
	pin_Z1 VARCHAR(100),
	pin_Z2 VARCHAR(100),
);
CREATE TABLE B3IP (
	fk_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	cell_name VARCHAR(100),
	pin_A VARCHAR(100),
	pin_Z1 VARCHAR(100),
	pin_Z2 VARCHAR(100),
);
CREATE TABLE D24L (
	fk_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	cell_name VARCHAR(100),
	pin_A VARCHAR(100),
	pin_B VARCHAR(100),
	pin_Z0 VARCHAR(100),
	pin_Z1 VARCHAR(100),
	pin_Z2 VARCHAR(100),
	pin_Z3 VARCHAR(100),
);
CREATE TABLE D24LP (
	fk_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	cell_name VARCHAR(100),
	pin_A VARCHAR(100),
	pin_B VARCHAR(100),
	pin_Z0 VARCHAR(100),
	pin_Z1 VARCHAR(100),
	pin_Z2 VARCHAR(100),
	pin_Z3 VARCHAR(100),
);
CREATE TABLE FA1 (
	fk_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	cell_name VARCHAR(100),
	pin_CI VARCHAR(100),
	pin_A VARCHAR(100),
	pin_B VARCHAR(100),
	pin_S VARCHAR(100),
	pin_CO VARCHAR(100),
);
CREATE TABLE FA1A (
	fk_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	cell_name VARCHAR(100),
	pin_CI VARCHAR(100),
	pin_A VARCHAR(100),
	pin_B VARCHAR(100),
	pin_S VARCHAR(100),
	pin_CO VARCHAR(100),
);
CREATE TABLE FA1AP (
	fk_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	cell_name VARCHAR(100),
	pin_CI VARCHAR(100),
	pin_A VARCHAR(100),
	pin_B VARCHAR(100),
	pin_S VARCHAR(100),
	pin_CO VARCHAR(100),
);
CREATE TABLE FA1P (
	fk_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	cell_name VARCHAR(100),
	pin_CI VARCHAR(100),
	pin_A VARCHAR(100),
	pin_B VARCHAR(100),
	pin_S VARCHAR(100),
	pin_CO VARCHAR(100),
);
CREATE TABLE HA1 (
	fk_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	cell_name VARCHAR(100),
	pin_A VARCHAR(100),
	pin_B VARCHAR(100),
	pin_S VARCHAR(100),
	pin_CO VARCHAR(100),
);
CREATE TABLE HA1P (
	fk_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	cell_name VARCHAR(100),
	pin_A VARCHAR(100),
	pin_B VARCHAR(100),
	pin_S VARCHAR(100),
	pin_CO VARCHAR(100),
);
CREATE TABLE FDS2 (
	fk_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	cell_name VARCHAR(100),
	pin_D VARCHAR(100),
	pin_CP VARCHAR(100),
	pin_CR VARCHAR(100),
	pin_Q VARCHAR(100),
	pin_QN VARCHAR(100),
);
CREATE TABLE FDS2L (
	fk_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	cell_name VARCHAR(100),
	pin_D VARCHAR(100),
	pin_CP VARCHAR(100),
	pin_CR VARCHAR(100),
	pin_LD VARCHAR(100),
	pin_Q VARCHAR(100),
	pin_QN VARCHAR(100),
);
CREATE TABLE FDS2LP (
	fk_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	cell_name VARCHAR(100),
	pin_D VARCHAR(100),
	pin_CP VARCHAR(100),
	pin_CR VARCHAR(100),
	pin_LD VARCHAR(100),
	pin_Q VARCHAR(100),
	pin_QN VARCHAR(100),
);
CREATE TABLE FDS2P (
	fk_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	cell_name VARCHAR(100),
	pin_D VARCHAR(100),
	pin_CP VARCHAR(100),
	pin_CR VARCHAR(100),
	pin_Q VARCHAR(100),
	pin_QN VARCHAR(100),
);
CREATE TABLE FT2 (
	fk_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	cell_name VARCHAR(100),
	pin_CP VARCHAR(100),
	pin_CD VARCHAR(100),
	pin_Q VARCHAR(100),
	pin_QN VARCHAR(100),
);
CREATE TABLE FT2P (
	fk_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	cell_name VARCHAR(100),
	pin_CP VARCHAR(100),
	pin_CD VARCHAR(100),
	pin_Q VARCHAR(100),
	pin_QN VARCHAR(100),
);
CREATE TABLE FT4 (
	fk_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	cell_name VARCHAR(100),
	pin_CP VARCHAR(100),
	pin_SD VARCHAR(100),
	pin_Q VARCHAR(100),
	pin_QN VARCHAR(100),
);
CREATE TABLE FT4P (
	fk_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	cell_name VARCHAR(100),
	pin_CP VARCHAR(100),
	pin_SD VARCHAR(100),
	pin_Q VARCHAR(100),
	pin_QN VARCHAR(100),
);
CREATE TABLE LD1X4 (
	fk_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	cell_name VARCHAR(100),
	pin_G VARCHAR(100),
);
CREATE TABLE LD1X4P (
	fk_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	cell_name VARCHAR(100),
	pin_G VARCHAR(100),
);
CREATE TABLE LS1 (
	fk_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	cell_name VARCHAR(100),
	pin_D1 VARCHAR(100),
	pin_C1 VARCHAR(100),
	pin_D2 VARCHAR(100),
	pin_C2 VARCHAR(100),
	pin_Q VARCHAR(100),
	pin_QN VARCHAR(100),
);
CREATE TABLE LS1P (
	fk_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	cell_name VARCHAR(100),
	pin_D1 VARCHAR(100),
	pin_C1 VARCHAR(100),
	pin_D2 VARCHAR(100),
	pin_C2 VARCHAR(100),
	pin_Q VARCHAR(100),
	pin_QN VARCHAR(100),
);
CREATE TABLE LSR0 (
	fk_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	cell_name VARCHAR(100),
	pin_S VARCHAR(100),
	pin_R VARCHAR(100),
	pin_Q VARCHAR(100),
	pin_QN VARCHAR(100),
);
CREATE TABLE LSR0P (
	fk_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	cell_name VARCHAR(100),
	pin_S VARCHAR(100),
	pin_R VARCHAR(100),
	pin_Q VARCHAR(100),
	pin_QN VARCHAR(100),
);
CREATE TABLE LSR2 (
	fk_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	cell_name VARCHAR(100),
	pin_S VARCHAR(100),
	pin_R VARCHAR(100),
	pin_G VARCHAR(100),
	pin_SD VARCHAR(100),
	pin_RD VARCHAR(100),
	pin_Q VARCHAR(100),
	pin_QN VARCHAR(100),
);
CREATE TABLE BTS4 (
	fk_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	cell_name VARCHAR(100),
	pin_A VARCHAR(100),
	pin_E VARCHAR(100),
	pin_Z VARCHAR(100),
);
CREATE TABLE BTS4P (
	fk_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	cell_name VARCHAR(100),
	pin_A VARCHAR(100),
	pin_E VARCHAR(100),
	pin_Z VARCHAR(100),
);
CREATE TABLE BTS5 (
	fk_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	cell_name VARCHAR(100),
	pin_A VARCHAR(100),
	pin_E VARCHAR(100),
	pin_Z VARCHAR(100),
);
CREATE TABLE BTS5P (
	fk_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	cell_name VARCHAR(100),
	pin_A VARCHAR(100),
	pin_E VARCHAR(100),
	pin_Z VARCHAR(100),
);
CREATE TABLE FD2TS (
	fk_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	cell_name VARCHAR(100),
	pin_D VARCHAR(100),
	pin_CP VARCHAR(100),
	pin_CD VARCHAR(100),
	pin_RD VARCHAR(100),
	pin_Z VARCHAR(100),
	pin_Q VARCHAR(100),
);
CREATE TABLE FD2TSP (
	fk_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	cell_name VARCHAR(100),
	pin_D VARCHAR(100),
	pin_CP VARCHAR(100),
	pin_CD VARCHAR(100),
	pin_RD VARCHAR(100),
	pin_Z VARCHAR(100),
);
CREATE TABLE RAM1 (
	fk_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	cell_name VARCHAR(100),
	pin_D VARCHAR(100),
	pin_WR VARCHAR(100),
	pin_WRN VARCHAR(100),
	pin_RD VARCHAR(100),
	pin_ZN VARCHAR(100),
	pin_QN VARCHAR(100),
);
CREATE TABLE input (
	fk_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	wire_name VARCHAR(100),
);
CREATE TABLE output (
	fk_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	wire_name VARCHAR(100),
);
CREATE TABLE gids (
	fk_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	gate VARCHAR(100),
);
